stages:
  - diff
  - lint
  - unit-tests
  - e2e-tests
variables:
  KUBECTL: v1.19.3
  KIND: v0.11.1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
diff:
  stage: diff
  image:
    name: $CI_REGISTRY_GO/golang:1.17
    entrypoint: [ "" ]
  tags:
    - go
  before_script:
    - cd documentation/gen && go run .
  script:
    - test -z "$(git diff 2> /dev/null)" || exit "Documentation is not generated, issue \`cd documentation/gen && go run .\` and commit the result"
    - test -z "$(git ls-files --others --exclude-standard 2> /dev/null)" || exit "Documentation created untracked files, cannot proceed"
  only:
    - merge_requests
    - branches
tidy:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/golang:1.17
    entrypoint: [""]
  tags:
    - go
  script:
    - go mod tidy
    - test -z "$(git diff 2> /dev/null)" || exit 'Go modules not tidied, issue \`go mod tidy\` and commit the result'
  only:
    - merge_requests
    - branches
golangci_lint:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/lint:1.33
    entrypoint: [""]
  tags:
    - go
  script:
    - golangci-lint run --enable-all --timeout=10m
  only:
    - merge_requests
    - branches
lint-commit-msg:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/check-commit:v2.1.0
    entrypoint: [""]
  tags:
    - go
  script:
      - /check
  only:
    - merge_requests
unit-tests:
  stage: unit-tests
  image:
    name: $CI_REGISTRY_GO/golang:1.17
    entrypoint: [""]
  tags:
    - go
  script:
    - apt update
    - go build -v .
    - go test -v ./...
  only:
    - merge_requests
    - branches
.kind_deployment:
  stage: e2e-tests
  image: docker:stable
  services:
    - name: $CI_REGISTRY_GO/docker:18.09.7-dind
      alias: docker
  tags:
    - go
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_GO
  script:
    - apk add -U wget git go curl
    - wget -q -o /dev/null -O &> /dev/null /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -q -o /dev/null -O &> /dev/null /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - sed -i "s/K8S_VERSION/$K8S_VERSION/g" ".gitlab/kind-config.yaml"
    - sed -i "s~CI_REGISTRY_GO~$CI_REGISTRY_GO~g" ".gitlab/kind-config.yaml"
    - sed -i "s~FROM golang~FROM $CI_REGISTRY_GO/golang~g" "build/Dockerfile"
    - sed -i "s~FROM haproxytech/haproxy-alpine~FROM $CI_REGISTRY_GO/haproxy-alpine~g" "build/Dockerfile"
    - kind create cluster --name=dev --config=./.gitlab/kind-config.yaml
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "$HOME/.kube/config"
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "deploy/tests/e2e/client.go"
    - until kubectl get nodes -o wide;do sleep 2; done
    - CI_ENV=gitlab deploy/tests/create.sh
    - KIND_URL=docker go test -v ./deploy/tests/e2e/... --tags=e2e_parallel
    - KIND_URL=docker go test -v -p 1 ./deploy/tests/e2e/... --tags=e2e_sequential
  after_script:
    - kind delete cluster --name=dev
  only:
    - merge_requests
    - branches
k8s_18:
  only:
    - schedules
  variables:
    K8S_VERSION: v1.18.19
  extends: .kind_deployment
k8s_19:
  only:
    - schedules
  variables:
    K8S_VERSION: v1.19.11
  extends: .kind_deployment
k8s_20:
  only:
    - schedules
  variables:
    K8S_VERSION: v1.20.7
  extends: .kind_deployment
k8s_21:
  variables:
    K8S_VERSION: v1.21.1
  extends: .kind_deployment
